default_platform(:ios)

platform :ios do

  desc "Push a new Wallet.xcodeproj beta build to TestFlight"
  lane :wallet_beta do
    increment_build_number_release

    build_app(
      project: "./projects/Wallet/Wallet.xcodeproj",
      configuration: "Release",
      scheme: "iOS",
      clean: true
    )

    upload_to_testflight
  end

  lane :increment_build_number_release do
    xcconfig_path = './projects/Wallet/iOS/Supporting/Configurations/iOSRelease.xcconfig'
    project_version = get_xcconfig_value(
      path: xcconfig_path,
      name: 'CURRENT_PROJECT_VERSION'
    ).to_i

    project_version += 1
    
    update_xcconfig_value(
      path: xcconfig_path,
      name: 'CURRENT_PROJECT_VERSION',
      value: project_version.to_s
    )
  end
  
end
