default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number_release

    build_app(
      project: "./projects/Application/Application.xcodeproj",
      configuration: "Release",
      scheme: "iOS",
      clean: true
    )

    upload_to_testflight
  end

  lane :increment_build_number_release do
    xcconfig_path = './projects/Application/iOS/Supporting/Configurations/Release.xcconfig'
    project_version = get_xcconfig_value(
      path: xcconfig_path,
      name: 'CURRENT_PROJECT_VERSION'
    ).to_i

    project_version += 1
    
    update_xcconfig_value(
      path: xcconfig_path,
      name: 'CURRENT_PROJECT_VERSION',
      value: project_version.to_s
    )
  end
  
end
